version: '2'
services:
  zk:
    image: rawmind/alpine-zk:3.4.8-16
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: rawmind/alpine-kafka:0.9.0.1-2
    ports:
      - "9092:9092"
      - "7203:7203"
    links:
      - zk
    environment:
      - KAFKA_DELETE_TOPICS=true
      - KAFKA_ZK_HOST=zk
      - KAFKA_EXT_IP=kafka

  trifecta:
    image: chatu/trifecta
    ports:
      - "8888:8888"
    links:
     - zk:zk
     - kafka:kafka
    environment:
      - ZOOKEEPERS=zk:2181
    depends_on:
      - zk

  #opentsdb:
  #  image: petergrace/opentsdb-docker
  #  ports:
  #    - "4242:4242"
